# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Jonas A"
__copyright__ = "Copyright 2021, Jonas A"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/cnvkit_panel_of_normal.smk"
include: "rules/gatk_cnv_panel_of_normal.smk"
include: "rules/msi_sensor_pro_panel_of_normal.smk"
include: "rules/create_background_file.smk"
include: "rules/create_artifact_file.smk"


report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),
