$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: path to fasta reference file
      mappability:
        type: string
        description: path to fasta mappability file
  required:
    - samples
    - units
    - resources
    - default_container

  cnvkit_create_targets:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  cnvkit_create_anti_targets:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  cnvkit_build_normal_reference:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      mappability:
        type: string
        description: file with mappability information
      extra:
        type: string
        description: extra parameters sent to cnvkit_build_normal_reference

  bed_to_interval_list:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  preprocess_intervals:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      bin_length:
        type: string
        description: size of bin regions (WGS 1000, Exomes/target 0)
      padding:
        type: string
        description: bases added to design regions (WGS 0, Exomes/target 250)
      extra:
        type: string
        description: extra parameters sent to preprocess_intervals (-imr OVERLAPPING_ONLY)

  collect_read_counts:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters sent to collect_read_counts (needs -imr OVERLAPPING_ONLY)

  create_read_count_panel_of_normals:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters sent to create_read_count_panel_of_normals

  exomedepth_bam_list:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  exomedepth_reference:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters sent to exomedepth_reference

  msisensor_pro_scan:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  msisensor_pro_input_file:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  msisensor_pro_baseline:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters sent to msisensor_pro_baseline

  create_background_file:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      min_dp:
        type: integer
        description: min depth to be inculded in the background calculation
      max_af:
        type: float
        description: max variant allele freuqency to be inculded in the background calculation

  create_artifact_file:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      callers:
        type: array
        items:
            type: string
        description: list of variant callers to include

  svdb_build:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  svdb_export:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters sent to svdb_export

  purecn_interval_file:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      genome:
        type: string
        description: reference genome
      average_off_target_width:
        type: integer
        description: average bin size of off-target regions

  purecn_bam_list:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  purecn_coverage:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters sent to purecn_coverage
      intervals:
        type: string
        description: interval panel design file

  purecn_coverage_list:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container

  bcftools_merge:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters sent to bcftools_merge
      info_rules:
        type: string
        description: option how bcftools should merge info in the vcf file
      output_type:
        type: string
        description: output file zip option

  purecn_normal_db:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      genome:
        type: string
        description: reference genome
